global_secrets:
  - AgoraAppId
  - ApiClientServerUrl
  - AwsBedrockSituationExtractionPromptId
  - AwsBedrockHistoryExtractionPromptId
  - AwsBedrockMedicationExtractionPromptId
  - AwsBedrockProcedureExtractionPromptId
  - GoogleMapsSdkApiKey
  - RollbarEnvironment
  - RollbarPostClientItemAccessToken
